### ISSUE TITLE
Use d2l-localize-behavior

### ISSUE THREAD

**Issue by dlockhart** [BrightspaceUI/date-picker#22]
Now that it exists, swapping out `app-localize-behavior` for [d2l-localize-behavior](https://github.com/BrightspaceUI/localize-behavior) will allow the removal of the language resolution code.

Additionally, `d2l-intl` is no longer needed as `d2l-localize-behavior` contains all its time formatting and parsing APIs.

**Comment by jwong-d2l** [comment]
this seems to have been done?

**Comment by dlockhart** [comment]
Looks like it yes!
