### ISSUE TITLE
Support input styling

### ISSUE THREAD

**Issue by toddradigan** [BrightspaceUI/date-picker#24]
The date-picker does not currently offer styling options.  Example use cases:

* The date-picker height is governed by the input, which cannot be changed
** my use case requires 42px height to match other input elements

* No error state styling exists
** my use case requires the border to change colour to red (cinnabar) when the selected date is not valid

**Comment by dlockhart** [comment]
If the height of the date picker doesn't match that of other inputs, that should just be treated as a bug and should be fixed.

Error state styling should also be addressed as a feature improvement.

**Comment by toddradigan** [comment]
No problem, that makes sense.  Should I open those as separate issues?

**Comment by dlockhart** [comment]
Sure, sounds good!

**Comment by toddradigan** [comment]
Closing in favour of
https://github.com/BrightspaceUI/date-picker/issues/26 and https://github.com/BrightspaceUI/date-picker/issues/27
